# Generated by Django 4.0.6 on 2022-07-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('job_start', models.DateField()),
                ('job_money', models.IntegerField()),
                ('job_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.category')),
            ],
        ),
    ]
